use_frameworks!

target 'ACKReactiveExtensions_Example' do
  pod 'ACKReactiveExtensions', :path => '../'
  pod 'ACKReactiveExtensions/Argo', :path => '../'
  pod 'ACKReactiveExtensions/Reachability', :path => '../'
  
  target 'ACKReactiveExtensions_Tests' do
      pod 'Quick', '~> 0.9'
      pod 'Nimble', '~> 4.0'
  end
  
end
