use_frameworks!
inhibit_all_warnings!

target 'ACKReactiveExtensions_Example' do
    pod 'Result', '~> 3.1'
    pod 'ACKReactiveExtensions', :path => '../'
    pod 'ACKReactiveExtensions/Argo', :path => '../'
    pod 'ACKReactiveExtensions/Reachability', :path => '../'
    pod 'ACKReactiveExtensions/SDWebImage', :path => '../'
    pod 'ACKReactiveExtensions/WebKit', :path => '../'
    pod 'ACKReactiveExtensions/Realm', :path => '../'
    pod 'ACKReactiveExtensions/Marshal', :path => '../'
    
    target 'ACKReactiveExtensions_Tests' do
        pod 'Quick', '~> 0.10'
        pod 'Nimble', '~> 7.0'
        pod 'Curry', '~> 3.0'
    end
end
