# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap --platform iOS --cache-builds
script:
- set -o pipefail && xcodebuild -scheme ACKReactiveExtensionsArgo -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme ACKReactiveExtensionsMarshal -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme ACKReactiveExtensionsUIKit -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme ACKReactiveExtensionsWebKit -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme ACKReactiveExtensionsSDWebImage -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme ACKReactiveExtensionsReachability -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme ACKReactiveExtensionsRealm -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
