osx_image: xcode11.3
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=ACKReactiveExtensions
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage checkout
before_deploy:
- carthage archive --output "$FRAMEWORK_NAME.framework.zip"
script:
- travis_wait 60 carthage build --platform iOS --cache-builds --no-skip-current
- pod lib lint --allow-warnings --quick
deploy:
  provider: releases
  api_key:
    secure: b50PHNZVc8hh6DoEw5PMp3enqeI4MrOG15wLdr0Yox6REmi1ATnJbTkS04vANP2mxvWbKwIMfqE/oYvWcYehbHIKugSh8N4rOBLsVG99HJqnqKI+b/CMuMCKU5RVNfN6HGal/8+V2QyAjgEPM/sDUoZQLYIMBC2GAAxzbtA/cUv8KpT6WcXaxCNhwNbVFHgLktV1gH/sQNTl6SIgXyBNqsbEjiX+x/DeKR1kQ9A7N4OkfenXxFPVvLZrrsrYa1evGH5DCdmekUi4b7Ga2RtObxzpC+yTQoPE483bCdlWnReZ6JFqHSibaTQe0uCX1/hFcZSo9djxUaACGcy6ZYUMlnl9NalUYIpZdZj5AYvn7fy3qcNLAUI4fxwOXsyQE/LeBficbYjggzSUsV9gllNuU+5XsGllw5tQ7BJrGjp5XNugDSm24RtQo3epPTR5LbNn81Rv10bWl2UiThmpRRA88PbJjyhJQr/bjZxPgwfUbD6iNzX/aXc/ISGhIOgVwC6JQP7Iu9w5ZB284yN//GglbN2UiVQ97jmPNmN3rHP0feTYj9Jc+ubs60q1EIZj8wN+4A91RG/p9g0U/zvHhWnqxLwBrBnjSOQpn6l+oOHoQ3CuzGhj+IfOhhZNBiNcKc2FMKdJIxG4gjNJ4NG23CW3Wci+lAyc3Yon91H55l/+bTQ=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/ACKReactiveExtensions
    tags: true
