# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: objective-c
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- travis_wait 120 carthage bootstrap --platform iOS --cache-builds
script:
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - Argo" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - Marshal" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - UIKit" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - WebKit" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - SDWebImage" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - Reachability" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - Realm" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
# - travis_wait 60 pod lib lint --allow-warnings
