osx_image: xcode10
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=ACKReactiveExtensions
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- travis_wait 120 carthage bootstrap --platform iOS --cache-builds
before_deploy:
- travis_wait 120 carthage build --no-skip-current --platform iOS
- carthage archive --output "$FRAMEWORK_NAME.framework.zip"
script:
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - Argo" -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - Marshal" -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - UIKit" -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - WebKit" -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - SDWebImage" -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - Reachability" -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- set -o pipefail && xcodebuild -scheme "ACKReactiveExtensions - Realm" -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint --allow-warnings --quick
deploy:
  provider: releases
  api_key:
    secure: b50PHNZVc8hh6DoEw5PMp3enqeI4MrOG15wLdr0Yox6REmi1ATnJbTkS04vANP2mxvWbKwIMfqE/oYvWcYehbHIKugSh8N4rOBLsVG99HJqnqKI+b/CMuMCKU5RVNfN6HGal/8+V2QyAjgEPM/sDUoZQLYIMBC2GAAxzbtA/cUv8KpT6WcXaxCNhwNbVFHgLktV1gH/sQNTl6SIgXyBNqsbEjiX+x/DeKR1kQ9A7N4OkfenXxFPVvLZrrsrYa1evGH5DCdmekUi4b7Ga2RtObxzpC+yTQoPE483bCdlWnReZ6JFqHSibaTQe0uCX1/hFcZSo9djxUaACGcy6ZYUMlnl9NalUYIpZdZj5AYvn7fy3qcNLAUI4fxwOXsyQE/LeBficbYjggzSUsV9gllNuU+5XsGllw5tQ7BJrGjp5XNugDSm24RtQo3epPTR5LbNn81Rv10bWl2UiThmpRRA88PbJjyhJQr/bjZxPgwfUbD6iNzX/aXc/ISGhIOgVwC6JQP7Iu9w5ZB284yN//GglbN2UiVQ97jmPNmN3rHP0feTYj9Jc+ubs60q1EIZj8wN+4A91RG/p9g0U/zvHhWnqxLwBrBnjSOQpn6l+oOHoQ3CuzGhj+IfOhhZNBiNcKc2FMKdJIxG4gjNJ4NG23CW3Wci+lAyc3Yon91H55l/+bTQ=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/ACKReactiveExtensions
    tags: true
