name: Build

on: [pull_request, push]

jobs:
  tests:
    name: Build
    runs-on: macos-12
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: AckeeCZ/load-xcode-version@1.0
      - uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Build dependencies
        run: carthage build --cache-builds --use-xcframeworks
      - name: Build
        run: carthage build --cache-builds --use-xcframeworks --no-skip-current 