name: Build

on: [pull_request, push]

jobs:
  tests:
    name: Build
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: AckeeCZ/load-xcode-version@1.0
      - uses: actions/cache@v3.2.2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Build dependencies
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        run: carthage bootstrap --cache-builds --use-xcframeworks --platform iOS
      - name: Build
        run: carthage build --cache-builds --use-xcframeworks --no-skip-current --no-use-binaries  --platform iOS