name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  carthage:
    name: Upload Carthage binary 
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: AckeeCZ/load-xcode-version@1.0
      - uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Build dependencies
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        run: carthage build --cache-builds --use-xcframeworks
      - name: Build
        run: carthage build --cache-builds --use-xcframeworks --no-skip-current 
      - name: Archive
        run: | 
          DST=$PWD
          mkdir -p /tmp/ACKReactiveExtensions
          mv Carthage/Build/ACKReactiveExtensions*.xcframework /tmp/ACKReactiveExtensions
          cd /tmp
          zip -r "$DST/"ACKReactiveExtensions.xcframework.zip ACKReactiveExtensions
      - uses: xresloader/upload-to-github-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ACKReactiveExtensions.xcframework.zip
          tags: true
          draft: false
  cocoapods:
    name: Push podspec to Cocoapods trunk
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: AckeeCZ/load-xcode-version@1.0
      - name: Install gems
        run: bundle install
      - name: Push podspec
        run: bundle exec pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}