name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  carthage:
    name: Upload Carthage binary 
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@v1
      - uses: actions/cache@v4
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Build dependencies
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        run: carthage bootstrap --cache-builds --use-xcframeworks --platform iOS
      - name: Build
        run: carthage build --cache-builds --use-xcframeworks --no-skip-current --no-use-binaries --platform iOS
      - name: Archive
        run: | 
          DST=$PWD
          mkdir -p /tmp/ACKReactiveExtensions
          mv Carthage/Build/ACKReactiveExtensions*.xcframework /tmp/ACKReactiveExtensions
          cd /tmp
          zip -r "$DST/"ACKReactiveExtensions.xcframework.zip ACKReactiveExtensions
      - uses: xresloader/upload-to-github-release@v1.5.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ACKReactiveExtensions.xcframework.zip
          tags: true
          draft: false